apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "oficina_user"
  SPRING_DATASOURCE_PASSWORD: "Oficina12345!"
  SECURITY_JWT_SECRET: "jwt-aws-secret-123456789012345678901234567890"
