# Copie para newrelic-secret.yaml (arquivo IGNORADO pelo git, ver .gitignore) e preencha
# com a license key real antes de aplicar. Nunca commitar o arquivo preenchido.
#
#   cp newrelic-secret.example.yaml newrelic-secret.yaml
#   # edite newrelic-secret.yaml com a license key
#   kubectl create namespace newrelic --dry-run=client -o yaml | kubectl apply -f -
#   kubectl apply -f newrelic-secret.yaml
#
# O Secret precisa existir em DOIS namespaces com o mesmo nome:
#   - `newrelic`: consumido pelo Infrastructure agent (nri-bundle), que lê a chave `licenseKey`
#                 (configurado via global.customSecretLicenseKey em newrelic-values.yaml).
#   - `oficina`:  consumido pelo Instrumentation CR do k8s-agents-operator
#                 (06-newrelic-instrumentation.yaml), que só lê Secrets do próprio namespace — e
#                 espera a chave `new_relic_license_key` (nome fixo do operator, convenção
#                 diferente do resto do bundle). Por isso o Secret de `oficina` tem as duas chaves.
apiVersion: v1
kind: Secret
metadata:
  name: newrelic-license
  namespace: newrelic
type: Opaque
stringData:
  licenseKey: "__NEW_RELIC_LICENSE_KEY__"
---
apiVersion: v1
kind: Secret
metadata:
  name: newrelic-license
  namespace: oficina
type: Opaque
stringData:
  licenseKey: "__NEW_RELIC_LICENSE_KEY__"
  new_relic_license_key: "__NEW_RELIC_LICENSE_KEY__"
